// Objective-C API for talking to scrape Go package.
//   gobind -lang=objc scrape
//
// File is generated by gobind. Do not edit.

#ifndef __Scrape_H__
#define __Scrape_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Parse parses the input coded string and returns the download url
 */
FOUNDATION_EXPORT NSString* _Nonnull ScrapeParse(NSString* _Nullable in_);

#endif
