
// Objective-C API for talking to the following Go packages
//
//	scrape
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Scrape_FRAMEWORK_H__
#define __Scrape_FRAMEWORK_H__

#include "Scrape.objc.h"
#include "Universe.objc.h"

#endif
